import React, {useEffect, useState} from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FilterHub from '../components/Filters/FilterHub'
import ProductList from '../components/Product/ProductList'
import type allProdutos from '../components/Product/ProductList'


interface Data {
  data: {
    data: {
      allProdutos: {
        productTitle: string,
        price: number,
        rating: number,
        id: string,
        productImage: {
            url: string
        },
        stock: number
      }[]
    }
  }
}

const Home: NextPage<Data> = ({data: {data: {allProdutos: productdata}}}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FilterHub></FilterHub>
        <ProductList allProdutos={productdata} />
      </Layout>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://graphql.datocms.com/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'Authorization': `Bearer ${process.env.REACT_APP_DATOCMS_API_TOKEN}`,
        },
        body: JSON.stringify({
          query: `
          {
            allProdutos {
              id
              productTitle
              productImage {
                url
              }
              stock
              rating
              price
            }
          }
          `
        }),
      })
  const data = await res.json()
  return {
    props: {data}, // will be passed to the page component as props
  }
}

export default Home
